---
apiVersion: v1
kind: Service
metadata:
  name: tunasync-worker
  labels:
    app: tunasync
spec:
  ports:
    - port: 6000
  selector:
    app: tunasync
    tier: worker
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tunasync-worker-log-pv-claim
  labels:
    app: tunasync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tunasync-worker-mirror-pv-claim
  labels:
    app: tunasync
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunasync-worker
  labels:
    app: tunasync
spec:
  selector:
    matchLabels:
      app: tunasync
      tier: worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tunasync
        tier: worker
    spec:
      containers:
      - image: qiuyin/tunasync-worker:latest
        name: worker
        ports:
        - containerPort: 6000
          name: worker
        volumeMounts:
        - name: tunasync-worker-log-persistent-storage
          mountPath: /tunasync/log
        - name: config
          mountPath: /tunasync/config
          readOnly: true
        - name: tunasync-worker-mirror-persistent-storage
          mountPath: /tunasync/mirror
      volumes:
      - name: config
        configMap:
          name: worker.conf
          items:
          - key: "worker.conf"
            path: "worker.conf"
      - name: tunasync-worker-log-persistent-storage
        persistentVolumeClaim:
          claimName: tunasync-worker-log-pv-claim
      - name: tunasync-worker-mirror-persistent-storage
        persistentVolumeClaim:
          claimName: tunasync-worker-mirror-pv-claim
